<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Document</title>
</head>
<body>
    <?php
        $num = 537; //Número Inteiro
        echo $num, " = Número Inteiro <br/><br/>";

        $num = -13; //Número Negativo
        echo $num, " = Número Negativo <br/><br/>";

        $num = 0123; //Número Octal (Equivalente a 83 em decimal)
        echo $num, " = Número Octal <br/><br/>";

        $num = 0x1A; //Número hexadecimal (Equivalente a 26 em Número Decimal)
        echo $num, " = Número Hexadecimal <br/><br/>";

        $num = 1.234; //Número Flutuante
        echo $num, " = Número Flutuante <br/><br/>";

        $num = 4e23; //Número Científica
        echo $num, " = Número Científica <br/><br/>";
    ?>
</body>
</html>