<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Saida</title>
</head>
<body>
    <?php
        Print "Teste <br>";
        Print "Olá, Mundo\n <br>";
        Print "Escape 'chars' são de os mesmos como em C\n <br>";
        Print "Você pode ter quebras de linhas em uma string";
        Print 'Uma string pode usar "aspas-duplas". Isso é muito legal!<br>';
        Print "Ainda pode-se usar aspas simples dessa forma It\'s cool'<br>";
    ?>
    <?php
        echo "texto <br>";
        echo "Olá Mundo <br>";
        echo "Isso abrange <br>
        varias linhas. as novas linhas serão
        saída também.";
        echo "Isso abrange\nmultiplas linhas. A nova será \na saída também. <br>";
        echo "Caracteristicas Escaping são \"Como esse\". <br>";
    ?>
</body>
</html>