<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Saida</title>
</head>
<body>
    <?php
        Print "Teste";
        Print "Olá, Mundo\n <br>";
        Print "Escape 'chars' são de os mesmos como em C\n <br>";
        Print "Você pode ter quebras de linhas em uma string";
        Print 'Uma string pode usar "aspas-duplas". Isso é muito legal!<br>';
        Print "Ainda pode-se usar aspas simples dessa forma It\'s cool'<br>";
    ?>
    
</body>
</html>